# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 18:04
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import shop.money.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('myshop', '0002_auto_20180606_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myshop.Product')),
                ('unit_price', shop.money.fields.MoneyField(decimal_places=3, help_text='Net price for this product', verbose_name='Unit price')),
                ('product_code', models.CharField(max_length=255, unique=True, verbose_name='Product code')),
                ('signup_date', models.DateField(default=django.utils.timezone.now, verbose_name='Signed Up')),
                ('placeholder', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='Membership Details', to='cms.Placeholder')),
            ],
            options={
                'verbose_name': 'Membership',
            },
            bases=('myshop.product',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
