# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cms_pages',
            field=models.ManyToManyField(blank=True, help_text='Choose list view this product shall appear on.', through='myshop.ProductPage', to='cms.Page'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.Manufacturer', verbose_name='Manufacturer'),
        ),
    ]
